FROM ghcr.io/astral-sh/uv:debian-slim
WORKDIR /app
COPY common/pyproject.toml common/pyproject.toml
COPY common/uv.lock common/uv.lock
COPY common/src common/src 
COPY relay/pyproject.toml relay/pyproject.toml
COPY relay/uv.lock relay/uv.lock
RUN uv --project relay sync
COPY relay/main.py relay/main.py
COPY relay/models.py relay/models.py
ENV PYTHONUNBUFFERED=1
ENV FASTAPI_MODE=run
CMD uv --project relay run fastapi ${FASTAPI_MODE} relay/main.py --port $PORT --host 0.0.0.0