FROM ghcr.io/astral-sh/uv:debian-slim
RUN apt-get update && apt-get install -y ffmpeg
COPY recorder/pyproject.toml .
COPY recorder/uv.lock .
RUN uv sync
COPY recorder/main.py .
ENV PYTHONUNBUFFERED=1
CMD uv run fastapi run main.py --port $PORT
