FROM ghcr.io/astral-sh/uv:debian-slim
COPY common/pyproject.toml common/pyproject.toml
COPY common/uv.lock common/uv.lock
COPY common/src common/src 
COPY relay/pyproject.toml relay/pyproject.toml
COPY relay/uv.lock relay/uv.lock
RUN uv --project relay sync
COPY relay/main.py relay/main.py
ENV PYTHONUNBUFFERED=1
CMD uv --project relay run fastapi run relay/main.py --port $PORT