[project]
name = "admin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "common[auth]",
    "firebase-admin>=7.1.0",
]

[tool.uv.sources]
common = { path = "../common", editable = true }
