"""use array for allowed roles

Revision ID: 6020521257c3
Revises: 173b78c47672
Create Date: 2026-01-12 07:25:17.900151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6020521257c3'
down_revision: Union[str, Sequence[str], None] = '173b78c47672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum("user", "admin", name="role_enum")
    role_enum.create(op.get_bind())
    op.add_column('device', sa.Column('allowed_roles', sa.ARRAY(sa.Enum('user', 'admin', name='role_enum', create_constraint=True)), server_default='{user}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'allowed_roles')
    sa.Enum(name="role_enum").drop(op.get_bind())
    # ### end Alembic commands ###
