"""Make user role nullable

Revision ID: a373bdd516ef
Revises: 7d2f4c4c2a1b
Create Date: 2026-01-21 21:56:43.544693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a373bdd516ef'
down_revision: Union[str, Sequence[str], None] = '7d2f4c4c2a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='role_enum'),
               nullable=True,
               existing_server_default=sa.text("'user'::role_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='role_enum'),
               nullable=False,
               existing_server_default=sa.text("'user'::role_enum"))
    # ### end Alembic commands ###
