"""add allowed roles to device table

Revision ID: cacd5f4c54b1
Revises: 15bdfb8dc7c9
Create Date: 2026-01-11 14:35:01.563377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cacd5f4c54b1'
down_revision: Union[str, Sequence[str], None] = '15bdfb8dc7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device",
        sa.Column(
            "allowed_roles", sa.JSON(), nullable=False, server_default='["user"]'
        ),
    )
    op.alter_column("device", "allowed_roles", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'allowed_roles')
    # ### end Alembic commands ###
