CREATE USER moja WITH LOGIN PASSWORD 'moja';
CREATE DATABASE moja OWNER moja;

CREATE USER relay_user WITH LOGIN PASSWORD 'relay';
CREATE DATABASE relay OWNER relay_user;

REVOKE ALL ON DATABASE moja FROM PUBLIC;
REVOKE ALL ON DATABASE relay FROM PUBLIC;
